name: Code Linting Check

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Run Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js and Cache Dependencies
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm" # Saves time on subsequent runs

      - name: Install Dependencies
        run: npm ci

      - name: Execute Lint Command
        run: npm run lint
